### PR TITLE
Biome blending

### PR DESCRIPTION
**Pull request by gwtnz**
Makes more gradual transitions between biome regions.

### CODE REVIEW

**Comment by agwilt** [comment]
This sounds awesome!

**Comment by Oussamarer** [comment]
goddamn you guys are making great peogress

**Comment by agwilt** [comment]
Now all we need is RPG elements and a singleplayer campaign :stuck_out_tongue_winking_eye:

**Comment by agwilt** [comment]
Actually, that would be really cool. We could add a "mapgen" that creates a complete Middle-Earth world, and add one or two "bosses" like dragons or Balrogs.

It might take a bit of work, though.

**Comment by Amaz1** [comment]
I'm not a massive fan of biome blend, as it can look ugly (e.g. https://imgur.com/a/EM4Yu), but of course, that's just my opinion, and others may think otherwise!
So, I'll add this as a setting, if that is alright with you, @gwtnz. I've got all of the code written, and I just need to commit and push it!

**Comment by gwtnz** [comment]
Sounds good @Amaz1 It does make things look a little weird in places, possibly some parameters to tweak to fix that, but it definitely looks odd when the biome region is really small. Feel free to incorporate how you see fit :)

**Comment by gwtnz** [comment]
Made an update to extend the blending in 3D (Y axis) to do its thing on cliff faces also. Some examples here : http://imgur.com/a/sgpyG . Still doesn't look so great with Mordor edges, as nothing in the vicinity looks remotely similar, but other biomes look ok.

**Comment by Amaz1** [comment]
Thanks!
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/813cf06918ddcce7769dc65ec7b348119f08b66e

If you want to enable it, add ```biome_blend = true``` to minetest.conf

If you want to improve on it, feel free to make a new pull!

**Comment by agwilt** [comment]
Talking about biomes, I saw these amazing looking rivergen maps on the LOTT website. Is there a way of using that mapgen?

**Comment by Amaz1** [comment]
Yeah, it's a C++ mapgen, so you would need to compile it yourself. This is the one with smaller rivers: https://github.com/duane-r/minetest/tree/valleys_c (This one: http://minetest.ig42.org/images/mapriver.png) and this is the one with bigger rivers: https://github.com/paramat/minetest/tree/rivergen (This one: http://minetest.ig42.org/images/mapriver2.png)

**Pull request closed without merging**
